apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
            - --init-file=/docker-entrypoint-initdb.d/init.sql
          env:
            - name: MYSQL_DATABASE
              value: universidade
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-scripts
            - mountPath: /var/lib/mysql
              name: mysql-data
      restartPolicy: Always
      volumes:
        - name: mysql-scripts
          configMap:
            name: mysql-scripts-init
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
status: {}
