apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30000

  selector:
    io.kompose.service: php
  type: NodePort
status:
  loadBalancer: {}

