apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: php
    spec:
      containers:
        - args:
             - /bin/bash
             - -c
             - ' apt-get update && rm /etc/apt/preferences.d/no-debian-php && apt-get install -y php-mysql && docker-php-ext-install mysqli && docker-php-ext-enable mysqli && echo ''ServerName localhost'' >> /etc/apache2/apache2.conf && exec apache2-foreground '
          image: thiagooczdev/cadastro-alunos:1.0
          name: php
          ports:
            - containerPort: 80
          resources: 
            requests:
              cpu: "300m"
            limits:
              cpu: "600m"
      restartPolicy: Always

status: {}