version: '3'
services:
  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      
  mysql:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password", "--init-file=/docker-entrypoint-initdb.d/init.sql"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universidade
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: always
volumes:
  mysql_data:

